name: deploy

on:

  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Select environment
        options:
        - 167.99.233.37
        - api.fonoster.net

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ github.event.inputs.choice }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSHKEY }}
          passphrase: ${{ secrets.DIGITALOCEAN_PASSPHRASE }}
          script: |
            set -e
            cd /opt
            docker run --rm \
              -e CONFIG_PATH=$(pwd)/fonoster/config \
              --volume /var/run/docker.sock:/var/run/docker.sock \
              --volume $(pwd)/fonoster:/out:rw \
              --entrypoint="/update.sh" \
              fonoster/fonoster
