name: unit tests
on:
  workflow_dispatch:
  push:
    paths:
    - 'mods/**'
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare environment
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Installing dependency
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Running tests
        run: |
          npm install
          chmod +x node_modules/.bin/cross-env
          npm run build
          npm test
