version: "3"

services:

  webui:
    build:
      context: .
      dockerfile: ./mods/webui/Dockerfile

  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile

  routr:
    ports:
      - 4567:4567
    volumes:
      - ./etc/log4j2.yml:/opt/routr/config/log4j2.yml:ro

  asterisk:
    build:
      context: .
      dockerfile: ./asterisk/Dockerfile
    ports:
      - 6060:6060
      - 8088:8088

  redis:
    ports:
      - 127.0.0.1:6379:6379

  vault:
    ports:
      - 8200:8200

  fluent:
    ports:
      - 24224:24224
  
  elasticsearch:
    ports:
      - 9200:9200

  minio:
    ports:
      - 9000:9000
      - 9001:9001
